---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "hami-dra-driver.name" . }}-kubelet-plugin
  namespace: {{ include "hami-dra-driver.namespace" . }}
  labels:
    {{- include "hami-dra-driver.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "hami-dra-driver.selectorLabels" (dict "context" . "componentName" "kubelet-plugin") | nindent 6 }}
  {{- with .Values.kubeletPlugin.updateStrategy }}
  updateStrategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  template:
    metadata:
      {{- with .Values.kubeletPlugin.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "hami-dra-driver.templateLabels" . | nindent 8 }}
        {{- include "hami-dra-driver.selectorLabels" (dict "context" . "componentName" "kubelet-plugin") | nindent 8 }}
    spec:
      {{- if .Values.kubeletPlugin.priorityClassName }}
      priorityClassName: {{ .Values.kubeletPlugin.priorityClassName }}
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "hami-dra-driver.serviceAccountName" . }}-kubeletplugin
      {{- with .Values.kubeletPlugin.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
      - name: init-container
        image: {{ include "hami-dra-driver.fullimage" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        securityContext:
          {{- toYaml .Values.kubeletPlugin.containers.init.securityContext | nindent 10 }}
        command: [bash, /usr/bin/kubelet-plugin-prestart.sh]
        env:
        - name: NVIDIA_DRIVER_ROOT
          value: {{ .Values.nvidiaDriverRoot | quote }}
        - name: NVIDIA_VISIBLE_DEVICES
          value: void
        - name: KUBELET_REGISTRAR_DIRECTORY_PATH
          value: {{ .Values.kubeletPlugin.kubeletRegistrarDirectoryPath | quote }}
        - name: KUBELET_PLUGINS_DIRECTORY_PATH
          value: {{ .Values.kubeletPlugin.kubeletPluginsDirectoryPath | quote }}
        {{- with .Values.kubeletPlugin.containers.init.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        volumeMounts:
        - name: driver-root-parent
          mountPath: /driver-root-parent
          {{- if eq "/" .Values.nvidiaDriverRoot }}
          readOnly: true
          {{- else }}
          mountPropagation: HostToContainer
          {{- end }}
      containers:
      - name: gpus
        image: {{ include "hami-dra-driver.fullimage" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        securityContext:
          {{- toYaml .Values.kubeletPlugin.containers.gpus.securityContext | nindent 10 }}
        command: ["bash", "-c"]
        args:
        - |-
          # Conditionally mask the params file to prevent this container from
          # recreating any missing GPU device nodes. This is necessary, for
          # example, when running under nvkind to limit the set GPUs governed
          # by the plugin even though it has cgroup access to all of them.
          if [ "${MASK_NVIDIA_DRIVER_PARAMS}" = "true" ]; then
            cp /proc/driver/nvidia/params root/gpu-params
            sed -i 's/^ModifyDeviceFiles: 1$/ModifyDeviceFiles: 0/' root/gpu-params
            mount --bind root/gpu-params /proc/driver/nvidia/params
          fi
          hami-kubelet-plugin -v $(LOG_VERBOSITY)
        {{- with .Values.kubeletPlugin.containers.gpus.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- if (gt (int .Values.kubeletPlugin.containers.gpus.healthcheckPort) 0) }}
        startupProbe:
          grpc:
            port: {{ .Values.kubeletPlugin.containers.gpus.healthcheckPort }}
            service: liveness
          failureThreshold: 60
          periodSeconds: 10
          timeoutSeconds: 10
        livenessProbe:
          grpc:
            port: {{ .Values.kubeletPlugin.containers.gpus.healthcheckPort }}
            service: liveness
          failureThreshold: 3
          periodSeconds: 30
          timeoutSeconds: 10
        {{- end }}
        lifecycle:
          postStart:
            exec:
              command: ["/bin/bash", "-c", "/usr/bin/vgpu-init.sh {{ .Values.driver.vgpuInitPath }}"]
        env:
        - name: LOG_VERBOSITY
          value: {{ .Values.logVerbosity | quote }}
        - name: MASK_NVIDIA_DRIVER_PARAMS
          value: {{ .Values.maskNvidiaDriverParams | quote }}
        - name: NVIDIA_DRIVER_ROOT
          value: {{ .Values.nvidiaDriverRoot | quote }}
        - name: NVIDIA_VISIBLE_DEVICES
          value: void
        - name: CDI_ROOT
          value: {{ .Values.driver.cdiRoot | quote }}
        - name: NVIDIA_MIG_CONFIG_DEVICES
          value: all
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: IMAGE_NAME
          value: {{ include "hami-dra-driver.fullimage" . }}
        {{- if .Values.nvidiaCDIHookPath }}
        - name: NVIDIA_CDI_HOOK_PATH
          value: {{ .Values.nvidiaCDIHookPath | quote }}
        {{- end }}
        {{- if .Values.featureGates }}
        - name: FEATURE_GATES
          value: "{{ range $key, $value := .Values.featureGates }}{{ $key }}={{ $value }},{{ end }}"
        {{- end }}
        - name: KUBELET_REGISTRAR_DIRECTORY_PATH
          value: {{ .Values.kubeletPlugin.kubeletRegistrarDirectoryPath | quote }}
        - name: KUBELET_PLUGINS_DIRECTORY_PATH
          value: {{ .Values.kubeletPlugin.kubeletPluginsDirectoryPath | quote }}
        {{- if (gt (int .Values.kubeletPlugin.containers.gpus.healthcheckPort) 0) }}
        - name: HEALTHCHECK_PORT
          value: {{ .Values.kubeletPlugin.containers.gpus.healthcheckPort | quote }}
        {{- end }}
        {{- with .Values.kubeletPlugin.containers.gpus.env }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- if .Values.deviceConfig.enabled }}
        - name: DEVICE_CONFIG_FILE
          value: /config/device-config.json
        {{- end }}
        volumeMounts:
        - name: plugins-registry
          mountPath: {{ .Values.kubeletPlugin.kubeletRegistrarDirectoryPath | quote }}
        - name: plugins
          mountPath: {{ .Values.kubeletPlugin.kubeletPluginsDirectoryPath | quote }}
          mountPropagation: Bidirectional
        - name: cdi
          mountPath: {{ .Values.driver.cdiRoot | quote }}
        - name: driver-root
          mountPath: /driver-root
          mountPropagation: HostToContainer
        - name: host-vgpu
          mountPath: {{ .Values.driver.vgpuInitPath | quote }}
        - name: host-tmp
          mountPath: {{ .Values.driver.hostTmp | quote }}
        {{- if .Values.deviceConfig.enabled }}
        - name: device-config
          mountPath: /config
          readOnly: true
        {{- end }}
        {{- if and .Values.featureGates (and (hasKey .Values.featureGates "PassthroughSupport") .Values.featureGates.PassthroughSupport) }}
        - name: host-root
          mountPath: /host-root
          mountPropagation: HostToContainer
          readOnly: true
        - name: sysfs
          mountPath: /sys/
          mountPropagation: Bidirectional
        - name: procfs
          mountPath: /proc/
          mountPropagation: Bidirectional
        {{- end }}
      volumes:
      - name: plugins-registry
        hostPath:
          path: {{ .Values.kubeletPlugin.kubeletRegistrarDirectoryPath | quote }}
          type: ""
      - name: plugins
        hostPath:
          path: {{ .Values.kubeletPlugin.kubeletPluginsDirectoryPath | quote }}
          type: ""
      - name: cdi
        hostPath:
          path: {{ .Values.driver.cdiRoot | quote }}
          type: ""
      - name: driver-root-parent
        hostPath:
          {{- if eq "/" .Values.nvidiaDriverRoot }}
          path: "/"
          {{- else }}
          path: {{ dir (trimSuffix "/" .Values.nvidiaDriverRoot) }}
          {{- end }}
          type: DirectoryOrCreate
      - name: driver-root
        hostPath:
          path: {{ .Values.nvidiaDriverRoot | quote }}
          type: DirectoryOrCreate
      - name: host-vgpu
        hostPath:
          path: {{ .Values.driver.vgpuInitPath | quote }}
          type: DirectoryOrCreate
      - name: host-tmp
        hostPath:
          path: {{ .Values.driver.hostTmp | quote }}
          type: ""
      {{- if .Values.deviceConfig.enabled }}
      - name: device-config
        configMap:
          name: {{ include "hami-dra-driver.name" . }}-device-config
      {{- end }}
      {{- if and .Values.featureGates (and (hasKey .Values.featureGates "PassthroughSupport") .Values.featureGates.PassthroughSupport) }}
      - name: host-root
        hostPath:
          path: /
          type: Directory
      - name: sysfs
        hostPath:
          path: /sys/
          type: Directory
      - name: procfs
        hostPath:
          path: /proc/
          type: Directory
      {{- end }}
      {{- with .Values.kubeletPlugin.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.kubeletPlugin.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.kubeletPlugin.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
